{
    "task" : "charades",
    "paths": {
        "ckpt_dir": "./ckpt",
        "cache_dir" : "./data_pkl/",
        "feature_path": "/storage_fast/rjliang/charades/i3d",
        "glove_path": "/storage_fast/rjliang/glove/glove.840B.300d.txt",
        "train_path": "./data/charades_gt/train.json",
        "test_path": "./data/charades_gt/test.json",
        "val_path": ""
    },
  "train": {
    "epochs": 100,
    "batch_size": 128,
    "lr": 0.0008,
    "warmup_proportion": 0.05,
    "clip_norm": 1.0
  },
    "dataprocess":{
        "video_augmentation": {
                                "unchanged": None
                                # "erosion":    0.05,
                                # "dilation":    0.05,
                              },
        "sample_type": "truncation",
        "label_threshold": 0.01
    },
  "model": {
        "name": "MultiTeacher",
        "vlen": 64,
        "tlen": 64,
        "vdim": 1024,
        "dim": 128,
        "num_heads": 4,
        "word_dim": 300,
        "char_dim": 100,
        "droprate": 0.2
    },
    "loss":
    {   t0_path: "./results/charades_BAN_train_logits.pkl",
        t0_cof: 1.0,
        t0_temperature: 3,
        t1_path: "./results/charades_EMAT_train_logits.pkl",
        t1_cof: 1.0,
        t1_temperature: 3,
        t2_path: "./results/charades_SeqPAN_train_logits.pkl",
        t2_cof: 1.0,
        t2_temperature: 3
    }
}