{
    "task" : "anet",
    "paths": {
        "ckpt_dir": "./ckpt",
        "cache_dir" : "./data_pkl/",
        "feature_path": "/storage_fast/rjliang/activitynet/c3d",
        "glove_path": "/storage_fast/rjliang/glove/glove.840B.300d.txt",
        "train_path": "./data/anet_c3d_gt/train.json",
        "test_path": "./data/anet_c3d_gt/test.json",
        "val_path": ""
    },

    "train": {
        "epochs": 100,
        "batch_size": 16,
        "lr": 0.0001,
        "warmup_proportion": 0.00,
        "clip_norm": 1.0
    },
    "dataprocess":{
        "video_augmentation": {
                                "unchanged": None
                                # "erosion":    0.05,
                                # "dilation":    0.05,
                              },
        "sample_type": "truncation",
        "label_threshold": 0.01
    },
    "model": {
        "name": "OneTeacher",
        "vlen": 100,
        "tlen": 100,
        "vdim": 512,
        "dim": 128,
        "num_heads": 4,
        "word_dim": 300,
        "char_dim": 100,
        "droprate": 0.2
    },
    "loss":
    {
        sd: 1.0,
        t0: 1.0,
        temperature: 3
    }
}